# Generated by Django 2.2.1 on 2019-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_images_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.CharField(max_length=12),
        ),
    ]
